//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAnalyticsServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationRule
    {
        public long Cause { get; set; }
        public long Сonsequence { get; set; }
        public double Confidence { get; set; }
    
        public virtual DetailInfo DetailInfo { get; set; }
        public virtual DetailInfo DetailInfo1 { get; set; }
    }
}
