//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAnalyticsServer.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoAnalyticsEntities : DbContext
    {
        public AutoAnalyticsEntities()
            : base("name=AutoAnalyticsEntities")
        {
            //Здесь будем вручную делать соединение. Надо конечно через конфиг, но у меня нет пока времени с ним разбираться,
            //поэтому будет такая временная "затычка".


        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssociationRule> AssociationRule { get; set; }
        public virtual DbSet<DetailInfo> DetailInfo { get; set; }
    }
}
