//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAnalyticsServer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailInfo()
        {
            this.AssociationRule = new HashSet<AssociationRule>();
            this.AssociationRule1 = new HashSet<AssociationRule>();
        }
    
        public long Id { get; set; }
        public string DetGroup { get; set; }
        public string DetSubgroup { get; set; }
        public string Detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociationRule> AssociationRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociationRule> AssociationRule1 { get; set; }
    }
}
